name: dot-net

on:
  push:
    branches:
      - dot-net
    tags:
      - '*'

  workflow_dispatch:

concurrency:
  group: dot-net-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-libs:
    name: dot-net for ${{ matrix.os }} on ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        arch: [x64, arm64]
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            6.0.x
            7.0.x

      - name: Check dotnet
        run: dotnet --info

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Install Python dependencies
        shell: bash
        run: |
          python3 -m pip install --upgrade pip jinja2

      - name: Install .NET workloads
        shell: bash
        run: |
          if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            dotnet workload install ios
          elif [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            dotnet workload install wasm-tools
          fi

      - name: build nuget packages
        shell: bash
        run: |
          cd scripts/
          # 修改 run.sh 脚本的执行权限
          chmod +x ./run.sh
          # 根据操作系统环境设置环境变量
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            export SKIP_IOS=1
          fi
          ./run.sh
          ls -lh packages || echo "packages directory not found"

      - uses: actions/upload-artifact@v4
        name: upload nuget packages
        with:
          name: nuget-packages-${{ matrix.os }}-${{ matrix.arch }}
          path: scripts/packages/*.nupkg

      - name: publish .Net packages to nuget.org
        if: github.repository == 'yuyixg/PortAudioSharp2'
        shell: bash
        env:
          API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          if [ -d "scripts/packages" ]; then
            cd scripts/packages
            dotnet nuget push ./*.nupkg --skip-duplicate --api-key $API_KEY --source https://api.nuget.org/v3/index.json
          else
            echo "scripts/packages directory does not exist, skipping package push"
            exit 0
          fi
